# Use the official MongoDB Docker image
FROM mongo:latest

# Set a custom data directory (optional)
# You can use a different directory if needed
# Example:
# RUN mkdir -p /data/db

# Expose the default MongoDB port
EXPOSE 27017

# Start MongoDB when the container runs
CMD ["mongod"]